	CREATE DATABASE EMPLOYEE_DB;

	CREATE TABLE DEPARTMENT(
	DEPARTMENT_ID INT PRIMARY KEY,
	NAME VARCHAR(45),
	LOCATION VARCHAR(45));

	CREATE TABLE EMPLOYEE_DETAILS(
	EMPLOYEE_DETAILS_ID INT PRIMARY KEY,
	EMPLOYEE_ID VARCHAR(45),
	SARLARY FLOAT,
	ADDRESS_1 VARCHAR(45),
	ADDRESS_3 VARCHAR(45),
	);

	CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRSTNAME VARCHAR(45),
    LASTNAME VARCHAR(45),
	SSN VARCHAR (9),
	DEPARTMENT_DEPARTMENT_ID INT,
	EMPLOYEE_DETAILS_EMP_DETAILS_ID INT,

	FOREIGN KEY(DEPARTMENT_DEPARTMENT_ID) 
	REFERENCES DEPARTMENT(DEPARTMENT_ID),

	FOREIGN KEY(EMPLOYEE_DETAILS_EMP_DETAILS_ID) 
	REFERENCES EMPLOYEE(EMPLOYEE_ID),

	)
	